name: Terraform CI

on:
  pull_request:
    paths:
      - '**.tf'
      - '.github/workflows/terraform_ci.yaml'

jobs:
  terraform:
    name: Terraform Format and Validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "~1.3"

      - name: Terraform Format Check
        run: terraform fmt -check -recursive
        
      - name: Terraform Init
        run: |
          for dir in $(find . -type f -name "*.tf" -exec dirname {} \; | sort -u); do
            echo "Initializing Terraform in $dir"
            cd $dir
            terraform init -backend=false
            cd - > /dev/null
          done

      - name: Terraform Validate
        run: |
          for dir in $(find . -type f -name "*.tf" -exec dirname {} \; | sort -u); do
            echo "Validating Terraform in $dir"
            cd $dir
            terraform validate
            cd - > /dev/null
          done
