name: Validate Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validate:
    name: Validate PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Check PR Title
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            build
            ci
            chore
            revert

      - name: Validate PR Description
        run: |
          if [ -z "${{ github.event.pull_request.body }}" ]; then
            echo "Pull request description is empty. Please provide a description."
            exit 1
          fi

      - name: Check for Required Labels
        uses: mheap/github-action-required-labels@v5
        with:
          mode: minimum
          count: 1
          labels: "bug, enhancement, documentation, dependencies, feature"

      - name: Check File Changes
        run: |
          git fetch origin ${{ github.base_ref }}
          changed_files=$(git diff --name-only origin/${{ github.base_ref }})
          
          if echo "$changed_files" | grep -q "\.tf$"; then
            echo "Terraform files changed. Please ensure terraform-ci workflow passes."
          fi
